### ISSUE TITLE
Keep info of the last request to the image instead of the first

### ISSUE THREAD

**Issue by SharbelOkzan** [polarspetroll/EmailTracker#2]
First of all, thanks for creating this very convenient tool!

I'd like to use it to track emails (instead of installing extensions). But the problem is that it stores info about the first time the image is opened, which defies the purpose, as the email client may render the image when I copy/paste into the email.

It would be nice if it stores the first and last requests to the image (or all requests if possible).

I'm not familiar enough with Golang but I'd try to work on a pr if you think that my suggestion is feasible,  please let me know :)

**Comment by polarspetroll** [comment]
Thanks for the suggestion. I also encountered the same issue while using it for services like Protonmail, Outlook, etc.. and I noticed the tracker is storing my own info as the target while I'm pasting the image. This happens because usually the email providers try to fetch the image to show you the result of image on your template. However, not all email providers work the same way. As I used it last time on gmail, the tracker works fine since I blocked the first HTTP request from google. But other services like outlook don't fetch the image by their own server which makes it very complicated to identify whether the request is coming from the email service or it's actually the target which opened the email. In this case I might track all requests as you suggested. Unfortunately based on previous experience if I store all requests the output becomes so large and I don't have much space on my database to store them all so I might completely change the database or maybe use some free SQL service. 

Anyways, thanks for the suggestion.
